### ISSUE TITLE
Proposal: Standardize Code Formatting and Linting with Industry Practices

### ISSUE THREAD

**Issue by geekayush** [spyshiv/commit-g#5]
### Summary

Introduce automated code formatting and linting to the repository using industry-standard tools (ESLint and Prettier). This will help maintain consistent coding style, reduce code review friction, catch common errors early, and improve overall code quality.

### Motivation

- Ensure consistent code style across the entire codebase.
- Prevent common syntax and stylistic errors before code review.
- Automate repetitive formatting tasks, saving developer time.
- Make the contribution process smoother and more approachable for new contributors.

### Implementation Overview

1. **Add ESLint and Prettier as dev dependencies.**
   - Install `eslint`, `prettier`, `eslint-config-prettier`, and `eslint-plugin-prettier`.
2. **Create configuration files:**
   - `.eslintrc.json` for linting rules.
   - `.prettierrc` for formatting rules.
3. **Update `package.json` scripts:**
   - Add scripts for `lint` and `format`.
4. **Add a GitHub Actions workflow:**
   - Run lint and format checks on pull requests.
5. **Document the setup:**
   - Add instructions to `CONTRIBUTING.md`.

#### .eslintrc.json
```json
{
  "env": {
    "browser": true,
    "es2021": true,
    "node": true
  },
  "extends": ["eslint:recommended", "plugin:prettier/recommended"],
  "plugins": ["prettier"],
  "rules": {
    "prettier/prettier": "error"
  }
}
```

#### .prettierrc
```json
{
  "semi": true,
  "singleQuote": true,
  "trailingComma": "all"
}
```

#### package.json scripts
```json
"scripts": {
  "lint": "eslint . --ext .js",
  "format": "prettier --write ."
}
```

#### GitHub Actions Workflow (.github/workflows/lint-format.yml)
```yaml
name: Lint and Format

on: [push, pull_request]

jobs:
  lint-format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm ci
      - run: npm run lint
      - run: npm run format -- --check
```

### Acceptance Criteria

- All JavaScript files must pass lint and format checks before merging.
- CI workflow must fail if linting or formatting fails.
